import { cryptoColors } from '../constants/styledConstants';

export const headerItem = [
  {
    idItem: 'requestItem',
    resourcesKey: 'requestItem',
    name: 'Request',
    path: '/',
  },
  {
    idItem: 'battlesItem',
    resourcesKey: 'battlesItem',
    name: 'Battles',
    path: '/battles',
  },
  {
    idItem: 'storyItem',
    resourcesKey: 'storyItem',
    name: 'Story',
    path: '/story',
  },
];

export const hpDropdown = [
  { key: 1, text: '50 HP', value: 50 },
  { key: 2, text: '100 HP', value: 100 },
  { key: 3, text: '150 HP', value: 150 },
  { key: 4, text: '200 HP', value: 200 },
  { key: 5, text: '300 HP', value: 300 },
  { key: 6, text: '500 HP', value: 500 },
];

export const sidebarItems = [
  {
    type: 'link',
    idItem: 'requestItem',
    resourcesKey: 'requestItem',
    image: '/static/sidebarItems/battle.svg',
    imageHover: '/static/sidebarItems/activePerson.svg',
    name: 'Request',
    path: '/',
  },
  {
    type: 'link',
    idItem: 'battlesItem',
    resourcesKey: 'battlesItem',
    image: '/static/sidebarItems/battle.svg',
    imageHover: '/static/sidebarItems/activeBattle.svg',
    name: 'Battles',
    path: '/battles',
  },
  {
    type: 'link',
    idItem: 'storyItem',
    resourcesKey: 'storyItem',
    image: '/static/sidebarItems/story.svg',
    imageHover: '/static/sidebarItems/storyActive.svg',
    name: 'Story',
    path: '/story',
  },
  {
    type: 'modal',
    idItem: 'warriors',
    resourcesKey: 'requestItem',
    image: '/static/sidebarItems/warriors.svg',
    imageHover: '/static/sidebarItems/activeWarriors.svg',
    name: 'TOP Warriors',
  },
  {
    type: 'modal',
    idItem: 'crypto',
    resourcesKey: 'battlesItem',
    image: '/static/sidebarItems/crypto.svg',
    imageHover: '/static/sidebarItems/activeCrypto.svg',
    name: 'TOP Crypto',
  },
  {
    type: 'logout',
    idItem: 'logout',
    resourcesKey: 'battlesItem',
    image: '/static/sidebarItems/logoutItem.svg',
    imageHover: '/static/sidebarItems/activeLogout.svg',
    name: 'Logout',
  },
];

export const modalDataCrypto = [
  {
    name: 'BCH',
    logo: '/static/cryptoList/bch/logo-bch.svg',
    person: '/static/cryptoList/bch/person-bch.svg',
    flag: '/static/cryptoList/bch/flag-bch.svg',
    mainColor: cryptoColors.bch_tree_poppy,
    progressColor: 'orange',
    cryptoCode: 'BINANCE:BCHUSD',
  },
  {
    name: 'DASH',
    logo: '/static/cryptoList/dash/logo-dash.svg',
    person: '/static/cryptoList/dash/person-dash.svg',
    flag: '/static/cryptoList/dash/flag-dash.svg',
    mainColor: cryptoColors.dash_denim,
    progressColor: 'blue',
    cryptoCode: 'BITFINEX:DSHUSD',
  },
  {
    name: 'EOS',
    logo: '/static/cryptoList/eos/logo-eos.svg',
    person: '/static/cryptoList/eos/person-eos.svg',
    flag: '/static/cryptoList/eos/flag-eos.svg',
    mainColor: cryptoColors.eos_black,
    progressColor: 'black',
    cryptoCode: 'BITFINEX:EOSUSD',
  },
  {
    name: 'BTC',
    logo: '/static/cryptoList/btc/logo-btc.svg',
    person: '/static/cryptoList/btc/person-btc.svg',
    flag: '/static/cryptoList/btc/flag-btc.svg',
    mainColor: cryptoColors.btc_tree_poppy,
    progressColor: 'orange',
    cryptoCode: 'BITFINEX:BTCUSD',
  },
  {
    name: 'ETH',
    logo: '/static/cryptoList/eth/logo-eth.svg',
    person: '/static/cryptoList/eth/person-eth.svg',
    flag: '/static/cryptoList/eth/flag-eth.svg',
    mainColor: cryptoColors.eth_cornflower_blue,
    progressColor: 'blue',
    cryptoCode: 'BITFINEX:ETHUSD',
  },
  {
    name: 'LTC',
    logo: '/static/cryptoList/ltc/logo-ltc.svg',
    person: '/static/cryptoList/ltc/person-ltc.svg',
    flag: '/static/cryptoList/ltc/flag-ltc.svg',
    mainColor: cryptoColors.ltc_cobalt,
    progressColor: 'blue',
    cryptoCode: 'BITFINEX:LTCUSD',
  },
  {
    name: 'NEO',
    logo: '/static/cryptoList/neo/logo-neo.svg',
    person: '/static/cryptoList/neo/person-neo.svg',
    flag: '/static/cryptoList/neo/flag-neo.svg',
    mainColor: cryptoColors.neo_green_haze,
    progressColor: 'green',
    cryptoCode: 'BITFINEX:NEOUSD',
  },
  {
    name: 'ZEC',
    logo: '/static/cryptoList/zec/logo-zec.svg',
    person: '/static/cryptoList/zec/person-zec.svg',
    flag: '/static/cryptoList/zec/flag-zec.svg',
    mainColor: cryptoColors.zec_tulip_tree,
    progressColor: 'yellow',
  },
  {
    name: 'ZRX',
    logo: '/static/cryptoList/ox/logo-ox.svg',
    person: '/static/cryptoList/ox/person-ox.svg',
    flag: '/static/cryptoList/ox/flag-ox.svg',
    mainColor: cryptoColors.ox_mine_shaft,
    progressColor: 'grey',
    cryptoCode: 'BITFINEX:ZECUSD',
  },
  {
    name: 'WAVES',
    logo: '/static/cryptoList/waves/logo-waves.svg',
    person: '/static/cryptoList/waves/person-waves.svg',
    flag: '/static/cryptoList/waves/flag-waves.svg',
    mainColor: cryptoColors.waves_cerulean,
    progressColor: 'blue',
    cryptoCode: 'BINANCE:WAVESUSD',
  },
  {
    name: 'BAT',
    logo: '/static/cryptoList/bat/logo-bat.svg',
    person: '/static/cryptoList/bat/person-bat.svg',
    flag: '/static/cryptoList/bat/flag-bat.svg',
    mainColor: cryptoColors.bat_international_orange,
    progressColor: 'red',
    cryptoCode: 'BITFINEX:BATUSD',
  },
  {
    name: 'XMR',
    logo: '/static/cryptoList/xmr/logo-xmr.svg',
    person: '/static/cryptoList/xmr/person-xmr.svg',
    flag: '/static/cryptoList/xmr/flag-xmr.svg',
    mainColor: cryptoColors.xmr_blaze_orange,
    progressColor: 'orange',
    cryptoCode: 'BITFINEX:XMRUSD',
  },
  {
    name: 'XRP',
    logo: '/static/cryptoList/xrp/logo-xrp.svg',
    person: '/static/cryptoList/xrp/person-xrp.svg',
    flag: '/static/cryptoList/xrp/flag-xrp.svg',
    mainColor: cryptoColors.xrp_black,
    progressColor: 'black',
    cryptoCode: 'BITFINEX:XRPUSD',
  },
];

export const LoginModalWindow = [
  {
    idItem: 'logIn',
    resourcesKey: 'logIn',
    name: 'Log In',
  },
];

export const logInLinkItems = [
  {
    idItem: 'userAgreement',
    resourcesKey: 'userAgreement',
    name: 'Пользовательским соглашением,',
  },
  {
    idItem: 'privacyPolicy',
    resourcesKey: 'privacyPolicy',
    name: 'Политикой конфиденциальности,',
  },
  {
    idItem: 'cookiePolicy',
    resourcesKey: 'cookiePolicy',
    name: 'Политикой использования файлов cookie',
  },
];
