import { cryptoColors } from '../styledConstants';

export default [
  {
    name: 'BCH',
    logo: '/static/cryptoList/bch/logo-bch.svg',
    person: '/static/cryptoList/bch/person-bch.svg',
    flag: '/static/cryptoList/bch/flag-bch.svg',
    mainColor: cryptoColors.bch_tree_poppy,
    progressColor: 'orange',
    cryptoCode: 'BINANCE:BCHUSD',
  },
  {
    name: 'DASH',
    logo: '/static/cryptoList/dash/logo-dash.svg',
    person: '/static/cryptoList/dash/person-dash.svg',
    flag: '/static/cryptoList/dash/flag-dash.svg',
    mainColor: cryptoColors.dash_denim,
    progressColor: 'blue',
    cryptoCode: 'BITFINEX:DSHUSD',
  },
  {
    name: 'EOS',
    logo: '/static/cryptoList/eos/logo-eos.svg',
    person: '/static/cryptoList/eos/person-eos.svg',
    flag: '/static/cryptoList/eos/flag-eos.svg',
    mainColor: cryptoColors.eos_black,
    progressColor: 'black',
    cryptoCode: 'BITFINEX:EOSUSD',
  },
  {
    name: 'ETC',
    logo: '/static/cryptoList/etc/logo-etc.svg',
    person: '/static/cryptoList/etc/person-etc.svg',
    flag: '/static/cryptoList/etc/flag-etc.svg',
    mainColor: cryptoColors.etc_viridian_green,
    progressColor: 'teal',
    cryptoCode: 'BITFINEX:ETCUSD',
  },
  {
    name: 'BTC',
    logo: '/static/cryptoList/btc/logo-btc.svg',
    person: '/static/cryptoList/btc/person-btc.svg',
    flag: '/static/cryptoList/btc/flag-btc.svg',
    mainColor: cryptoColors.btc_tree_poppy,
    progressColor: 'orange',
    cryptoCode: 'BITFINEX:BTCUSD',
  },
  {
    name: 'ETH',
    logo: '/static/cryptoList/eth/logo-eth.svg',
    person: '/static/cryptoList/eth/person-eth.svg',
    flag: '/static/cryptoList/eth/flag-eth.svg',
    mainColor: cryptoColors.eth_cornflower_blue,
    progressColor: 'blue',
    cryptoCode: 'BITFINEX:ETHUSD',
  },
  {
    name: 'ICON',
    logo: '/static/cryptoList/icx/logo-icx.svg',
    person: '/static/cryptoList/icx/person-icx.svg',
    flag: '/static/cryptoList/icx/flag-icx.svg',
    mainColor: cryptoColors.icx_pelorous,
    progressColor: 'blue',
    cryptoCode: 'BINANCE:ICXUSD',
  },
  {
    name: 'LTC',
    logo: '/static/cryptoList/ltc/logo-ltc.svg',
    person: '/static/cryptoList/ltc/person-ltc.svg',
    flag: '/static/cryptoList/ltc/flag-ltc.svg',
    mainColor: cryptoColors.ltc_cobalt,
    progressColor: 'blue',
    cryptoCode: 'BITFINEX:LTCUSD',
  },
  {
    name: 'METAL',
    logo: '/static/cryptoList/mtl/logo-mtl.svg',
    person: '/static/cryptoList/mtl/person-mtl.svg',
    flag: '/static/cryptoList/mtl/flag-mtl.svg',
    mainColor: cryptoColors.mtl_shark,
    progressColor: 'black',
    cryptoCode: 'BINANCE:MTLUSD',
  },
  {
    name: 'NEO',
    logo: '/static/cryptoList/neo/logo-neo.svg',
    person: '/static/cryptoList/neo/person-neo.svg',
    flag: '/static/cryptoList/neo/flag-neo.svg',
    mainColor: cryptoColors.neo_green_haze,
    progressColor: 'green',
    cryptoCode: 'BITFINEX:NEOUSD',
  },
  {
    name: 'ZEC',
    logo: '/static/cryptoList/zec/logo-zec.svg',
    person: '/static/cryptoList/zec/person-zec.svg',
    flag: '/static/cryptoList/zec/flag-zec.svg',
    mainColor: cryptoColors.zec_tulip_tree,
    progressColor: 'yellow',
  },
  {
    name: 'ZRX',
    logo: '/static/cryptoList/ox/logo-ox.svg',
    person: '/static/cryptoList/ox/person-ox.svg',
    flag: '/static/cryptoList/ox/flag-ox.svg',
    mainColor: cryptoColors.ox_mine_shaft,
    progressColor: 'grey',
    cryptoCode: 'BITFINEX:ZECUSD',
  },
  {
    name: 'WAVES',
    logo: '/static/cryptoList/waves/logo-waves.svg',
    person: '/static/cryptoList/waves/person-waves.svg',
    flag: '/static/cryptoList/waves/flag-waves.svg',
    mainColor: cryptoColors.waves_cerulean,
    progressColor: 'blue',
    cryptoCode: 'BINANCE:WAVESUSD',
  },
  {
    name: 'BAT',
    logo: '/static/cryptoList/bat/logo-bat.svg',
    person: '/static/cryptoList/bat/person-bat.svg',
    flag: '/static/cryptoList/bat/flag-bat.svg',
    mainColor: cryptoColors.bat_international_orange,
    progressColor: 'red',
    cryptoCode: 'BITFINEX:BATUSD',
  },
  {
    name: 'XMR',
    logo: '/static/cryptoList/xmr/logo-xmr.svg',
    person: '/static/cryptoList/xmr/person-xmr.svg',
    flag: '/static/cryptoList/xmr/flag-xmr.svg',
    mainColor: cryptoColors.xmr_blaze_orange,
    progressColor: 'orange',
    cryptoCode: 'BITFINEX:XMRUSD',
  },
  {
    name: 'XRP',
    logo: '/static/cryptoList/xrp/logo-xrp.svg',
    person: '/static/cryptoList/xrp/person-xrp.svg',
    flag: '/static/cryptoList/xrp/flag-xrp.svg',
    mainColor: cryptoColors.xrp_black,
    progressColor: 'black',
    cryptoCode: 'BITFINEX:XRPUSD',
  },
];
