import { cryptoColors } from '../styledConstants';

export default [
  {
    name: 'BCH',
    logo: '/static/cryptoList/bch/logo-bch.svg',
    person: '/static/cryptoList/bch/person-bch.svg',
    flag: '/static/cryptoList/bch/flag-bch.svg',
    mainColor: cryptoColors.bch_tree_poppy,
  },
  {
    name: 'DASH',
    logo: '/static/cryptoList/dash/logo-dash.svg',
    person: '/static/cryptoList/dash/person-dash.svg',
    flag: '/static/cryptoList/bch/flag-dash.svg',
    mainColor: cryptoColors.dash_denim,
  },
  {
    name: 'EOS',
    logo: '/static/cryptoList/eos/logo-eos.svg',
    person: '/static/cryptoList/eos/person-eos.svg',
    flag: '/static/cryptoList/bch/flag-eos.svg',
    mainColor: cryptoColors.eos_black,
  },
  {
    name: 'ETC',
    logo: '/static/cryptoList/etc/logo-etc.svg',
    person: '/static/cryptoList/etc/person-etc.svg',
    flag: '/static/cryptoList/bch/flag-etc.svg',
    mainColor: cryptoColors.etc_viridian_green,
  },
  {
    name: 'BTC',
    logo: '/static/cryptoList/btc/logo-btc.svg',
    person: '/static/cryptoList/btc/person-btc.svg',
    flag: '/static/cryptoList/bch/flag-btc.svg',
    mainColor: cryptoColors.btc_tree_poppy,
  },
  {
    name: 'ETH',
    logo: '/static/cryptoList/eth/logo-eth.svg',
    person: '/static/cryptoList/eth/person-eth.svg',
    flag: '/static/cryptoList/bch/flag-eth.svg',
    mainColor: cryptoColors.eth_cornflower_blue,
  },
  {
    name: 'ICON',
    logo: '/static/cryptoList/icx/logo-icx.svg',
    person: '/static/cryptoList/icx/person-icx.svg',
    flag: '/static/cryptoList/bch/flag-icx.svg',
    mainColor: cryptoColors.icx_pelorous,
  },
  {
    name: 'LTC',
    logo: '/static/cryptoList/ltc/logo-ltc.svg',
    person: '/static/cryptoList/ltc/person-ltc.svg',
    flag: '/static/cryptoList/bch/flag-ltc.svg',
    mainColor: cryptoColors.ltc_cobalt,
  },
  {
    name: 'METAL',
    logo: '/static/cryptoList/mtl/logo-mtl.svg',
    person: '/static/cryptoList/mtl/person-mtl.svg',
    flag: '/static/cryptoList/bch/flag-mtl.svg',
    mainColor: cryptoColors.mtl_shark,
  },
  {
    name: 'NEO',
    logo: '/static/cryptoList/neo/logo-neo.svg',
    person: '/static/cryptoList/neo/person-neo.svg',
    flag: '/static/cryptoList/bch/flag-neo.svg',
    mainColor: cryptoColors.neo_green_haze,
  },
  {
    name: 'ZEC',
    logo: '/static/cryptoList/zec/logo-zec.svg',
    person: '/static/cryptoList/zec/person-zec.svg',
    flag: '/static/cryptoList/bch/flag-zec.svg',
    mainColor: cryptoColors.zec_tulip_tree,
  },
  {
    name: 'ZRX',
    logo: '/static/cryptoList/ox/logo-ox.svg',
    person: '/static/cryptoList/ox/person-ox.svg',
    flag: '/static/cryptoList/bch/flag-ox.svg',
    mainColor: cryptoColors.ox_mine_shaft,
  },
  {
    name: 'WAVES',
    logo: '/static/cryptoList/waves/logo-waves.svg',
    person: '/static/cryptoList/waves/person-waves.svg',
    flag: '/static/cryptoList/bch/flag-waves.svg',
    mainColor: cryptoColors.waves_cerulean,
  },
  {
    name: 'BAT',
    logo: '/static/cryptoList/bat/logo-bat.svg',
    person: '/static/cryptoList/bat/person-bat.svg',
    flag: '/static/cryptoList/bch/flag-bat.svg',
    mainColor: cryptoColors.bat_international_orange,
  },
  {
    name: 'XMR',
    logo: '/static/cryptoList/xmr/logo-xmr.svg',
    person: '/static/cryptoList/xmr/person-xmr.svg',
    flag: '/static/cryptoList/bch/flag-xmr.svg',
    mainColor: cryptoColors.xmr_blaze_orange,
  },
  {
    name: 'XRP',
    logo: '/static/cryptoList/xrp/logo-xrp.svg',
    person: '/static/cryptoList/xrp/person-xrp.svg',
    flag: '/static/cryptoList/bch/flag-xrp.svg',
    mainColor: cryptoColors.xrp_black,
  },
];
